name: CI

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3

    - name: Install dependencies
      run: |
        gem install rspec -v 3.7.0
        gem install rubocop
        gem install vcr -v 6.2
        gem install webmock -v 3.23
        gem install rexml -v 3.2.6
        gem install jwt -v 2.8.1
        gem install aws-sdk-sqs -v 1.70.0
        gem install aws-sdk-dynamodb -v 1.105.0
        gem install activesupport -v 7.1.3.2

    - name: Run tests
      run: bundle exec rspec

#    - name: Bundle install
#      run: |
#        bundle config path vendor/bundle
#        bundle install --jobs 4 --retry 3

#    - run: bundle exec rake
#    - name: Install dependencies
#      run: bundle install
#
#    - name: Run RuboCop
#      run: bundle exec rubocop
#
